var={"error_code": "0", "error_msg": "", "smzdm_id": "9177786080", "s": "6c947c2e9a771eaec81405450cff0c6b",
 "data": {"show_total": "99+", "rows": [{"article_hash_id": "alpznzeg", "article_channel_id": "154",
                                         "article_title": "230\u73af\u5883-799-230\u6d4b\u8bd5\u7528\u6237\u6cbb\u7406\u6807\u7b7e",
                                         "article_format_date": "06-26", "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/alpznzeg\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "alpznzeg", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "52e4a81fa5ed796c24f4920011a30de1", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/a.zdmimg.com\/202406\/26\/667b87334e8bd914.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u5f00\u4e1a\u4e00\u4e2a\u6708\uff0c\u6211\u8981\u8f6c\u8ba9\u4e86\u2026\u2026",
                                         "is_video": "0", "zhuanzai_id": "27886",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "av7k20z4", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/av7k20z4\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "av7k20z4", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "28d23c6959cb6d7db33e02b3c990126d", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "amm04lk4", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/amm04lk4\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "amm04lk4", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "7a4cf297ec14eeb0549d2076232ac4ec", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "a83dn807", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/a83dn807\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "a83dn807", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "f97f1953c6ca9538df7389ead7bccca4", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "a997x32o", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/a997x32o\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "a997x32o", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "6e548f17371aeec68111b81501c6e71e", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "a3gz95vk", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/a3gz95vk\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "a3gz95vk", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "ffdbd0137f4e34207cb4a9010ad44cd7", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "awxl92q4", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/awxl92q4\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "awxl92q4", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "6679796c0337df52fb361efac1cce4ed", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "alpznkwe", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/alpznkwe\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "alpznkwe", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "21cb6e90a5ac5cb841f949ee45927b9f", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "akmr0w79", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/akmr0w79\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "akmr0w79", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "5a4d96156ef2ffefb899be3fa245b27a", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "ag896e27", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/ag896e27\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "ag896e27", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "10a0c5ee207d627f18e15495bb1887bd", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "a5k6zwll", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/a5k6zwll\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "a5k6zwll", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "f73a5bdeef3bd528cf1d42d1ebefe003", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "a6ln2k8n", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/a6ln2k8n\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "a6ln2k8n", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "b3c0067777049356d2676a184539445c", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "apze49k9", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/apze49k9\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "apze49k9", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "28eb75a71a7464e44d80d1b35c226fd5", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "ax089nr3", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/ax089nr3\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "ax089nr3", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "6438916b040e17b7dccbee43ed056f12", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "a4w09gk8", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/a4w09gk8\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "a4w09gk8", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "1b82b02f67eced731fb94462d1849400", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "a78e2l3g", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/a78e2l3g\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "a78e2l3g", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "7dd15e238d1e0e0fd53670d5860113a9", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "aoo643wm", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/aoo643wm\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "aoo643wm", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "f6516f49d2ad07601f584a70864b0905", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "adwlp0rz", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/adwlp0rz\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "adwlp0rz", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "dbf31efb94db587d41dbf0b6b161fad4", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "a25rmpg7", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/a25rmpg7\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "a25rmpg7", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "f00f2f28ea3552ccc2acdbd42eb2a567", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"},
                                        {"article_hash_id": "and248g3", "article_channel_id": "154",
                                         "article_title": "\u6d4b\u8bd5\u6570\u636e1", "article_format_date": "06-20",
                                         "cell_type": "33025",
                                         "redirect_data": {"link": "https:\/\/post.m.smzdm.com\/zz\/p\/and248g3\/",
                                                           "link_title": "", "link_type": "zhuanzai",
                                                           "link_val": "and248g3", "sub_type": "detail",
                                                           "isv_code_second": "0_0_0_0_0_0_0_0_0_0",
                                                           "jd_isv_code": "0_0_0_0_0_0_0_0_0_0",
                                                           "md5_url": "387ec0e5004e9928ea44576ed2572e3c", "mp_path": "",
                                                           "mp_appid": "", "mp_type": "out_h5", "mp_tab": "0",
                                                           "scheme_url": ""}, "disable_edit": "0",
                                         "article_pic": "https:\/\/qna.smzdm.com\/202406\/20\/667419c3859fe2965.jpg_a200.jpg",
                                         "zhuanzai_from": "\u5c0f\u7ea2\u4e66",
                                         "article_subtitle": "\u9752\u5c9b\u7684\uff01\uff01\uff01\u9ebb\u9171\u6dae\u8089\u5929\u82b1\u677f\uff01\uff01",
                                         "is_video": "0", "zhuanzai_id": "27864",
                                         "article_interaction": {"article_comment": "0", "article_rating": "0",
                                                                 "article_pv": "0"},
                                         "user_data": {"referrals": "wyc230",
                                                       "avatar": "https:\/\/avatarimg.smzdm.com\/default\/9177786080\/658aa2a20ebfa4330-big.jpg",
                                                       "official_auth_icon": "https:\/\/res.smzdm.com\/images\/certificate\/chef_life_medal.gif"},
                                         "status_text": "\u5df2\u53d1\u5e03", "article_status_color": "#1da95d"}],
          "show_tab": "0"}}
# 利用jsonpath提取
from jsonpath import jsonpath
a=jsonpath(var,"$...article_hash_id")
print(a)

# 利用循环提取
list1=[]
num1=0
data=var["data"]["rows"]
for i in data:
    dic={}
    dic["article_hash_id"]=i["article_hash_id"]
    list1.append(dic)
    num1+=1
    if num1>31:
        break
print(list1)